### ISSUE TITLE
No data is being stored in the database

### ISSUE THREAD

**Issue by dissto** [Alimir/wp-ulike#29]
Im on a fresh WP 4.9.6 install running PHP7. Upon clicking the like button, it infinitly increases the count no matter if I am logged in or not.
But NO datas are stored in the database?!

Whats going on there?

**Comment by contemplate** [comment]
Hey @dissto I had this same issue and traced it back to IPv6 addresses not being saved in the database due to the varchar value being set to low.  Once I changed the IP column in the following tables to varchar(60) for wp_ulike, wp_ulike_activities, wp_ulike_comments, wp_ulike_forums everything saved fine.
