### ISSUE TITLE
User's like status doesn't work with persistent object caching

### ISSUE THREAD

**Issue by nturbanov** [Alimir/wp-ulike#77]
There's an issue with updating the object cache that arises when using persistent object caching (Redis, Memcached, etc.).

When a user clicks like their old like status is first checked and the new status is written to the database. This is problematic as checking the old status also updates the object cache and, alas, the old value is saved in the object cache.

The result of this is that the user can keep liking clicking the like button for as long the the object cache has the old status value. This updates the counter and writes wrong values in the database.

If the user refreshed the page, the status of the like button is also wrong. Ie. if a user likes an article and then refreshes, the button is still shown as if they haven't yet liked the article.

I have "Logged By Username" turned on, so the code affecting me is found in in the [loggedby_other_methods() method](https://github.com/Alimir/wp-ulike/blob/3efb57a29666f85c5a1ae7451b0807144d314713/inc/classes/class-wp-ulike.php#L213), but the same is happening in the other logging methods.

[get_user_status()](https://github.com/Alimir/wp-ulike/blob/3efb57a29666f85c5a1ae7451b0807144d314713/inc/classes/class-wp-ulike.php#L506) updates the object cache if it's empty and thus the old status value is written in it.

So I think the status should always be updated for the object cache when a user interaction happens.

**Comment by Alimir** [comment]
Dear @nturbanov 
Yes, I just noticed this bug and fixed the problem in commit below. Can you test it?
https://github.com/Alimir/wp-ulike/commit/f8080e210b8fab9efd61bab5ef536684d46a2ebe

**Comment by nturbanov** [comment]
Thanks for looking into it @Alimir 

f8080e2 disables the object caching completely. Sure it probably fixes the issue, but that's not a good idea as database queries will sky rocket in high traffic sites with lots of comments.

**Comment by Alimir** [comment]
@nturbanov 
This code refers to an old structure that should have been removed in version 4.2. In previous versions, this code had a structure that received the user's status as an array with just one request and assigned it to each button. However, when the number of users' records increased, the problem of slow query occurred.
So I changed this mode and now, for each button, one request is sent and since the item_id is different, we don't have a duplicate query problem.
However, with the addition of the new ulike_meta table, I'm looking for a new way to save all user status as a serialized array in this table, and then be able to reduce the number of user status requests again.

**Comment by Alimir** [comment]
@nturbanov I implemented the changes I wanted in the commit below. Currently, the status of users is stored and cached in the meta table, but I feel that this can be improved! But I have no idea right now!
https://github.com/Alimir/wp-ulike/commit/6b786630be3e5b3bba2d6c41c81627ce87c3cf09
